//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace ShiningInfomation.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        [Display(Name = "学生ID")]
        public string StudentID { get; set; }

        [Display(Name = "姓名")]
        public string StudentName { get; set; }

        [Display(Name = "学生Alias")]
        public string StudentAlias { get; set; }

        [Display(Name = "密码")]
        public string Password { get; set; }

        [Display(Name = "项目组")]
        public string Team { get; set; }

        [Display(Name = "座右铭")]
        public string Motto { get; set; }

        [Display(Name = "老师")]
        public string TeacherID { get; set; }

        [Display(Name = "闪亮小组")]
        public string GroupNum { get; set; }
        
        public virtual TeacherInfo TeacherInfo { get; set; }
    }
}
